# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/space-titanic',
                'doc_host': 'https://mix060514.github.io',
                'git_url': 'https://github.com/mix060514/space-titanic',
                'lib_path': 'space_titanic'},
  'syms': {'space_titanic.core': {'space_titanic.core.foo': ('core.html#foo', 'space_titanic/core.py')}}}